### ISSUE TITLE
TMI in the build output

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#114]
Running ./gradlew test outputs too much information. We don't need to see which tests passed on the console just those that failed. Also a bunch of stracktraces are being spat out for some reason.

**Comment by loosebazooka** [comment]
Details?

**Comment by patflynn** [comment]
https://travis-ci.org/GoogleCloudPlatform/gcloud-intellij/builds/84323954

**Comment by elharo** [comment]
We could kill the stated messages. The others are still useful. The stack
traces should be fixed. I think I filled a bug on that.

--
Elliotte Rusty Harold
on a mobile phone so please excuse weird autocorrects

**Comment by elharo** [comment]
https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/80 is most of the stack traces. Haven't yet figured out how to fix this.

**Comment by elharo** [comment]
fixed
