### ISSUE TITLE
Google Login failing for a user

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#125]
From user:
Android Studio Version: First got the error 2 nights ago on version 1.4 Build #AI-141.2288178, built on September 28, 2015
                                   I got the error again today on the same build as above before upgrading
                                   And I just got it again after updating via the Canary channel to version 1.5 Preview Build #AI-141.2314126, built on October 6, 2015

OS: Windows 10 Pro 64-bit

I'm not trying to authenticate through any browser, its an Android Studio/Google Cloud SDK (not sure which one) window (possibly a browser window). You can see what I'm talking about in the pictures below.

Here is the process I'm trying to follow:

1. In Android Studio click VCS -> Import into Version Control -> Upload Project to Google Cloud...:

![image](https://cloud.githubusercontent.com/assets/7862557/10484957/261d08be-7256-11e5-886e-f258784e0d80.png)

2. Then a window pops up for selecting a Google Cloud Project and when I click the drop down arrow, there's a window to sign in:

![image](https://cloud.githubusercontent.com/assets/7862557/10484961/2dd7b662-7256-11e5-807c-34ad9b1681dd.png)

3. Then for about 1/2 a second this window shows up:

![image](https://cloud.githubusercontent.com/assets/7862557/10484971/388362fa-7256-11e5-8329-52d383e05d86.png)

4. After that, I get this error:
![image](https://cloud.githubusercontent.com/assets/7862557/10484975/3d6e29f8-7256-11e5-88e3-428d3c6713ae.png)

5. I can click Ok to dismiss the error, but then the 3rd pic above comes back and never goes away.

**Comment by nbashirbello** [comment]
Looking into it...

**Comment by patflynn** [comment]
Thanks Nabila.   Priority wise this comes after TOS/Analytics.

**Comment by nbashirbello** [comment]
This problem seems to be a Windows bug not actually a bug in Android Studio. It seems to be a pretty common Windows problem. There are some potential fixes here (http://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install/class-not-registered-windows-10-edge/b4f5e1e6-94cf-4c4b-9146-2e0fe68cebd6) and here (http://www.tenforums.com/general-discussion/23989-class-not-registered-error-when-searching-clicking-links.html)

**Comment by patflynn** [comment]
My bad I should have mentioned I followed up with the user and they fixed this by changing their browser settings in Android Studio.
