### ISSUE TITLE
Moving from a captured snapshot to a pending snapshot doesn't change the stack frame

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#143]
1) start a debugger session https://docs.google.com/document/d/1cM1m6yHask_xnZ2E-L0gjo98aPbOWziFnwiK_ZKxzTw/edit#
2) Set a watchpoint
3) trigger it http://cloud-debugger-demo.appspot.com/gen
4) go to view it
5) add a new snapshot 
6) navigate to the untriggered snapshot in the snapshots UI
7) note that the stack state still reflects the information from the captured snapshot

expected result
switching to an uncaptured snapshot would clear the stack UI

**Comment by elharo** [comment]
This is also part of CloudDebugHistoricalSnapshots. That class is responsible for about 4 of our open bugs. I'm going to start by seeing if I can refactore that class so it's more conprehensible.

**Comment by elharo** [comment]
This may be in CloudDebugProcess.navigateToSnapshot 
In particular here:

                  if (result.getIsFinalState() != Boolean.TRUE || result.getStackFrames() == null) {
                    getBreakpointHandler().navigateTo(result);
                    return;
                  }

IN the case where esult.getStackFrames() == null we want to clear the frames panel. I'm not sure what method will do that. XDebugSession doesn't seem to allow it.

**Comment by elharo** [comment]
Maybe I can pass in an empty XExecutionStack to XDebugSession.setCurrentStackFrame()?

**Comment by patflynn** [comment]
YGIAGAM
