### ISSUE TITLE
Cloud Debugger: More precise message for not matching source context

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#145]
Right now, we do not differentiate between these scenarios:

1. the server sends us a null source context meaning there is no information for matching a git repo.
2. the server sent us a valid source context but it wasn't Git
3. the server sent us a valid source context, but we could not locate a suitable Git Repo that has that SHA

Right now, if we encounter any of these we show a generic message indicating that we "could not verify that the source is correct"
We should give more detailed info so the user knows how to address the problem.

**Comment by elharo** [comment]
Where is this? I don't see that string in our codebase.

**Comment by patflynn** [comment]
I'm not sure. This is a bug I pulled out of another system. I would expect the text to be in our CloudToolsBundle.properties under a clouddebug key.

**Comment by elharo** [comment]
This may happen in ProjectRepositoryValidator

**Comment by elharo** [comment]
Possiubly this is referring to this error

clouddebug.sourcedoesnotmatch=Your current source does not match what is running on the server.

used in CloudAttachDialog

    myWarningLabel2.setText(GctBundle.getString("clouddebug.sourcedoesnotmatch"));

**Comment by elharo** [comment]
and I think the code that displays this warning is here:

    else if (!mySyncResult.isDeterminable()) {
      setOKButtonText(getIsContinued() ? "Continue Anyway" : GctBundle.getString("clouddebug.attach.anyway"));
      myWarningLabel.setVisible(true);
      myWarningLabel2.setVisible(true);
      myInfoPanel.setVisible(true);
      myWarningLabel2.setText("Could not verify that current source matches module.");
    }

**Comment by elharo** [comment]
FYI see GcpHttpAuthDataProvider.isUrlGCP

**Comment by elharo** [comment]
getTargetRepository().getRemotes().getUrls()

but it really l9ooks like the non-Git case just can't happen
