### ISSUE TITLE
Help button goes to IDEA debugger help

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-intellij#149]
On the left hand toolbar of the cloud debugger pane, the blue question mark icon links to 

https://www.jetbrains.com/idea/help/debug-tool-window.html

I.e. the IDEA debugger help. We should instead link it to Cloud Debugger specific help.

**Comment by joaoandremartins** [comment]
Looking at plugin.xml, I can't find any toolWindow element. There are also no classes that inherit from ToolWindowFactory.

I'm assuming we're using the default Debug tool window, but where do we specify that?

I thought clicking Run/Debug Configuration could trigger showing the tool window, but I can't find anything relevant in AppEngineRunConfigurationType.java.

**Comment by elharo** [comment]
We are using the default debug tool pane. 

core-plugin/src/com/google/gct/idea/debugger/CloudDebugProcess.java is the class where we modify this pane in various ways. In particular look at the registerAdditionalActions method.

**Comment by elharo** [comment]
Do we want to put the help page on Github (where it would be part of this repository) or on devsite (which would require it going into Gogole's internal source repository)?

**Comment by patflynn** [comment]
For now the help page is going on devsite as Katie is writing it.
