### ISSUE TITLE
Can't build on Windows because fetchIdea.sh is Linux specific

### ISSUE THREAD

**Issue by Adam-Origamiiris** [GoogleCloudPlatform/gcloud-intellij#167]
Not sure this is the right place but I've been unable to build the plugin after pulling from git. 

What version of IDEA are you using?
IntelliJ community Edition 14.1.5
What version of Java are you using?
1.8.0_65 64 bit on Windows 7 and ran cmd as Admin
What did you do?
Cloned then then went into the folder and typed >gradlew plugin
What did you expect to see?
To see build complete or similar
What did you see instead?
with --debug I saw 
:loadIdea Failed 
> A problem occurred starting process 'comman ' .fetchIdea.sh

**Comment by loosebazooka** [comment]
Yeah it's a Linux script. You need to build on Linux at the moment

**Comment by Adam-Origamiiris** [comment]
Ahhh thank you,

**Comment by elharo** [comment]
I'm reopening this one. Low priority but we should figure out how to make it build on Windows, and at the very least mention this in CONTRIBUTING.md

**Comment by patflynn** [comment]
Before we fix this we should experiment with the gradle intellij plugin to
see if it solves this for us.

**Comment by patflynn** [comment]
I have a working build and am fixing tests on a PR that may fix this, so I recommend nobody else pick this up for now.
