### ISSUE TITLE
user-agent needs to always be passed as part of any RPC to GCP

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#174]
Cloud Repo, Cloud Debugger, AE deployments, etc should always include a useragent specific to our plugin/platform combo.

**Comment by elharo** [comment]
Any preference for what the user agent should be here?

**Comment by patflynn** [comment]
+markpell

Could we mirror browser user-agent structure and construct a composite user
agent from  $platform/$version $plugin/$version?  e.g. Android Studio/1.5
(Windows 10)  GoogleCloudTools/0.9-alpha.

Mark, are you guys using the user-agent for server-side analytics?  Do you
know what the recommended way to get this data into concord is?

**Comment by patflynn** [comment]
You can see how we construct our UA here:
https://cs.corp.google.com/#piper///depot/google3/third_party/py/googlecloudsdk/core/cli.py&l=50

Unfortunately concord does not provide direct access to the UA in the user
facing tables because they are worried about PII.  So we need to get them
to add a column to the table for each field in the UA we want to look at.
We want to look at all of them so we are in the process of getting them to
add them all, but it's a little slow going.  +Vilas Jagannath
<vilasj@google.com> is working on that.

**Comment by patflynn** [comment]
Adding to what Mark said; the current process for getting this data into
concord is:

1) Include it in the UA for service calls (after privacy/security approval).
2) Request concord team to parse this data and include it as a column in
the usage tables.

The turnaround is slow.

Cheers,

Vilas

**Comment by patflynn** [comment]
Is there a standard UA agent format for separating dimensions?

**Comment by patflynn** [comment]
We have been using space separated '/' separated pairs
<https://cs.corp.google.com/#piper///depot/google3/third_party/py/googlecloudsdk/core/cli.py&l=50>
which
conforms to the product token specification
<http://www.ietf.org/rfc/rfc2616.txt>.

**Comment by patflynn** [comment]
+elharo

**Comment by elharo** [comment]
I thiunk we're now done with this unless someone knows of another place where we're connecting over HTTP.
