### ISSUE TITLE
Remove dependency on org.apache.tools.ant.filters.ReplaceTokens when processing analytics property flag

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/gcloud-intellij#178]
Dependecy: "jar://$APPLICATION_HOME_DIR$/plugins/xslt-debugger/ant-1.7.1.jar!/"

**Comment by elharo** [comment]
@loosebazooka fixed this in https://github.com/GoogleCloudPlatform/gcloud-intellij/commit/7d7a630ec1e5f7ec866a09dcd8bf018cddc82a7b
