### ISSUE TITLE
Login icon is not visible after sign-out

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#191]
Steps to reproduce:

1) Start IntelliJ with the login plugin installed
2) Login to a Google account using the Google login icon in the toolbar
3) Logout from your account
4) observe that the space for the icon is still there, that the icon can still be hovered over and works, however the icon image is gone.
![screenshot from 2015-11-05 13 48 07](https://cloud.githubusercontent.com/assets/7862557/10978294/19ca6d20-83c4-11e5-8193-495dcc4fd615.png)

**Comment by elharo** [comment]
I can't immediately reproduce this. In my case, the icon changes from the picture i have on my Google account to a generic person figure, white on gray.

**Comment by patflynn** [comment]
strange.  I've just tried with a fresh project checkout, gradlew plugin, manual install, and this bug reproduces. (on linux)

**Comment by elharo** [comment]
It appears this only happens when an analytics ID is supplied; e.g. 

$  gradle   -DusageTrackerProperty=UA-1111111-2  devBuild

**Comment by patflynn** [comment]
This is being caused by the resource filtering corrupting our image files. @loosebazooka is gonna look into narrowing filtering to our properties files.
