### ISSUE TITLE
If no debuggable module is available for a project the module drop down is just empty

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#228]
Some kind of message should be displayed explaining to the user why they can't attach.

**Comment by joaoandremartins** [comment]
Yes, I meant to file this issue. On top of that, I found out that CDB also doesn't work if you have no instance alive, which makes sense, but isn't documented anywhere I could find.

We should probably add a hint that CDB won't work if you have no instance alive.

**Comment by loosebazooka** [comment]
![image](https://cloud.githubusercontent.com/assets/1304826/11667863/38daa726-9dc2-11e5-9070-cc674310fbb1.png)

how's this @elharo @patflynn

**Comment by elharo** [comment]
Not sure of the GUI standard here, but can we put an italic gray text in
the combobox itself saying woth the warning? and maybe deactivate the
popup?

On Tue, Dec 8, 2015 at 3:42 PM, Appu Goundan <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/1304826/11667863/38daa726-9dc2-11e5-9070-cc674310fbb1.png>
>
> how's this @elharo <https://github.com/elharo> @patflynn
> <https://github.com/patflynn>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/228#issuecomment-163012115>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by patflynn** [comment]
+1. That's the right way to handle it. The select box should be disabled and the contents should explain that there are no modules available. 

BTW @loosebazooka why is the 'Warning: unkown repositories are not supported' displayed in this case?

**Comment by loosebazooka** [comment]
Sorry that screenshot was outdated.

It's possible, but I realized that I'd probably have to make the code really weird to put in a non-module item.

Anyway uploading that as an alternative patch.
