### ISSUE TITLE
What happens if you cloud debug multiple projects at the same time?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#269]

**Comment by loosebazooka** [comment]
Things go nuts

**Comment by loosebazooka** [comment]
Should we only allow a single sessions?

**Comment by patflynn** [comment]
I think we have some fundamental model issues around setting snapshots when
multiple projects are being debugged that we need to talk about.

**Comment by elharo** [comment]
Per discussion, plan is to prevent multiple projects from being cloud debugged at same time.
