### ISSUE TITLE
I can't bring up the Cloud Debugger console view despite active sessions showing on the debug button.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#287]
![screenshot from 2015-12-04 15 02 43](https://cloud.githubusercontent.com/assets/7862557/11600521/35b52fdc-9a9b-11e5-9dbb-053c9d41dddf.png)

The debug button clearly shows '2' sessions active, but there's no bottom margin panel to bring them up.  Trying to reattach also fails to pop up the panels.  I just get a 3rd active session and no way to look at them.

**Comment by patflynn** [comment]
actually I think what was going on here is that the debug bottom margin panel was hidden.  The old debug session was stlil running and trying to reattach just created a new one.   It doesn't make sense to create two cdb sessions to the same project.

**Comment by patflynn** [comment]
@loosebazooka is this issue fixed by your one session at a time change?

**Comment by loosebazooka** [comment]
It looks like the root of this issue is the panel button on the bottom left to bring up all your panels. The secondary thing you were talking about seems to have been solved by the one session at a time thing.
