### ISSUE TITLE
When a background listener is stopped when closing the debug toolbar, it wont be started until the IDE starts up again.

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/gcloud-intellij#311]
Because of the way run configurations are constructed, it appears https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/3651c3043c2286b03caf9c02910707fb805ea1b4/core-plugin/src/com/google/gct/idea/debugger/CloudDebugRunConfiguration.java#L58 is only called once.

If we disable the poller when closing a debug window https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/3651c3043c2286b03caf9c02910707fb805ea1b4/core-plugin/src/com/google/gct/idea/debugger/ui/ExitDialog.java#L49, I don't think it'll start up again.

We probably have to think about putting the ensureWatcher call somewhere else?

**Comment by loosebazooka** [comment]
I think our stop dialog has to disable the "processtate" in the run configuration instead of stopping the watcher here.

**Comment by elharo** [comment]
Makes sense. Give it a try.
