### ISSUE TITLE
Remove Java logo from "Delete All snapshots" popup

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/gcloud-intellij#339]

**Comment by elharo** [comment]
I'm not sure what logo you're referring to. Is this the dialog?

![removealldialog](https://cloud.githubusercontent.com/assets/1005544/12174449/86774168-b52a-11e5-9e83-f4dfbc1e7a15.png)

**Comment by joaoandremartins** [comment]
This is what I mean. Maybe it's platform specific, as I see you're using Ubuntu and I'm using Mac.

<img width="403" alt="screen shot 2016-01-07 at 11 33 10 am" src="https://cloud.githubusercontent.com/assets/3290856/12175865/87d077ca-b532-11e5-8dc2-33d073713ad2.png">

**Comment by patflynn** [comment]
Maybe we're suggesting you go get a cup of coffee as this operation is going to take a long time?

**Comment by elharo** [comment]
This is a standard IntelliJ OK-cancel dialog. We don't set it up aside from adding the labels to UI elements. I'm not sure why that icon is there at all, except that someone at JetBrains must have liked it.

  @OkCancelResult
  public static int showOkCancelDialog(String message, @NotNull @Nls(capitalization = Nls.Capitalization.Title) String title, @NotNull String okText, @NotNull String cancelText, Icon icon, @Nullable DialogWrapper.DoNotAskOption doNotAskOption) {
    try {
      if (canShowMacSheetPanel()) {
        int result = MacMessages.getInstance().showYesNoDialog(title, message, okText, cancelText, null, doNotAskOption);
        return result == YES ? OK : CANCEL;
      }
    }
    catch (MessageException ignored) {/*rollback the message and show a dialog*/}
    catch (Exception reportThis) {LOG.error(reportThis);}

    return showDialog(message, title, new String[]{okText, cancelText}, 0, icon, doNotAskOption) == 0 ? OK : CANCEL;
  }

The Java icon does look suspiciously like a default icon when the regular icon can't be found. I wonder if this happens elsewhere in IDEA. Perhap this should be reported to JetBrains as a platform-specific Mac issue.

**Comment by joaoandremartins** [comment]
Filed https://youtrack.jetbrains.com/issue/IDEA-150269.

**Comment by joaoandremartins** [comment]
I just noticed this only appears on the "./gradlew runIdea" Run Configuration from IDEA. This instance seems to have a few differences (different shortcuts, different "Main" name on the toolbar, etc.) that I still don't know how to explain.

When I'm a normal IDEA instance, I get the IJ logo, which is OK.

**Comment by loosebazooka** [comment]
should we still keep this closed? or as an open question?
