### ISSUE TITLE
Add warning mentioning users must have running instances on their app to be able to take snapshots

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/gcloud-intellij#345]
The CDB API only returns debuggable modules which have alive instances. If no module does, the IntelliJ attach dialog only shows a generic error message.

I noticed there's no mention of the alive instances message anywhere in our docs. Is this on purpose, or should we say in the attach dialog something like "Ensure your application has alive instances so you can take snapshots"? I spent some time wondering why I couldn't attach and such a message would have saved me some time.

**Comment by patflynn** [comment]
what's an alive instance?  Is that in our error message?

**Comment by joaoandremartins** [comment]
In an app without resident instances (i.e., only has dynamic instances), it is possible for it to have 0 QPS and no instances spinned up. This is likely to happen on development environments.

In these circumstances, CDB won't fire from IntelliJ (or anywhere).

Our message doesn't allude to that, but it should IMO.

**Comment by patflynn** [comment]
Are you saying that if there are no live instances at the time that a
snapshot is set, that CDB won't hold onto the snapshot and configure it
once an instance is spun up?

**Comment by joaoandremartins** [comment]
No, the issue is you can't attach CDB to an app if it doesn't have any alive instances. Since you can't attach, you can't start a CDB debug session and you can't set breakpoints.

You need to first spin up an instance with a request in order to be able to attach CDB to the app. That request may or may not hit a breakpoint, if any is set.

I don't know what the behaviour is when you set a breakpoint without any alive instances.

**Comment by elharo** [comment]
Yes, this is an issue. 
Yes, we should update the docs. 
For the IDEA docs, just update them directly on github.
The general cloud debugger docs are in google3/devsite and can also be updated since this is an issue that affects all cloud debugger clients, not just the IDEA plugin.

**Comment by joaoandremartins** [comment]
As it turns out, it's now possible to attach without live instances, so I'll close this for the time being.

**Comment by patflynn** [comment]
Let's explore whether there's a low effort solution to this.  I'd prefer not to launch with this issue.

**Comment by akerekes** [comment]
Is it possible to ping the instance to have AppEngine reactivate it? Otherwise we could add to the error message currently displayed ("Please select a project with debuggable modules.") a link (with text "I cannot see my module") that would show the user a message in the dialog below the error message, that says "If you don't see the module you want to debug, make sure it is active (alive?) on AppEngine by sending a request to it or opening the webapp in a browser". Or something along these lines.

**Comment by joaoandremartins** [comment]
My favourite approach would be to add some text saying the Debugger doesn't work if there are no alive instances for a version.

Adding a pinging button would be optional, since it passes the idea that the product is broken but offers an easy workaround at the same time. However, we'd need to add some logic to refresh the debugees list which could be a bit hacky. (i.e., after clicking the button, the user wouldn't see anything new without first closing and reopening the dialog)

**Comment by patflynn** [comment]
@etanshaul or @akerekes, if either of you guys have time to look at this, I was talking to Erez last week and we'd really like to get this fixed for our next release.
