### ISSUE TITLE
rename the 'Google Cloud Tools Core'  plugin name to something sensible.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#354]
Both the 'core-plugin' and the 'Google Cloud Tools Core' plugin name are bad names.

1) Users looking at our plugin in the IJ repo aren't going to understand what distinction 'core' makes, since there are no other Google Cloud Tools plugins.
2) If we eventually refactor our plugins and break them out into pieces, for instance 'Cloud Debugger' plugin, 'Cloud Repo' plugin, 'App Engine' plugin, we won't want to have to make the user reinstall all these new plugins.  We'd rather the first install to imply the super-set of GCP tooling plugins, so that we can refactor it to depend on these new factored out plugins, and hopefully things will still work.
3) If we never do componentize our plugin, it's likely to stay a monolith and support multiple IJ SKUs through conditional plugin.xml includes. 

All that to say that we should probably just rename the plugin to 'Google Cloud Tools'..

**Comment by patflynn** [comment]
@GoogleCloudPlatform/cloud-tools-for-intellij, a penny for your thoughts.

**Comment by elharo** [comment]
Makes sense. "Google Cloud Tools", "Google Cloud Platform Tools",
or "Google Cloud Platform Plugin"

On Tue, Jan 12, 2016 at 5:12 PM, Patrick Flynn <notifications@github.com>
wrote:

> Both the 'core-plugin' and the 'Google Cloud Tools Core' plugin name are
> bad names.
>
> 1) Users looking at our plugin in the IJ repo aren't going to understand
> what distinction 'core' makes, since there are no other Google Cloud Tools
> plugins.
> 2) If we eventually refactor our plugins and break them out into pieces,
> for instance 'Cloud Debugger' plugin, 'Cloud Repo' plugin, 'App Engine'
> plugin, we won't want to have to make the user reinstall all these new
> plugins. We'd rather the first install to imply the super-set of GCP
> tooling plugins, so that we can refactor it to depend on these new factored
> out plugins, and hopefully things will still work.
> 3) If we never do componentize our plugin, it's likely to stay a monolith
> and support multiple IJ SKUs through conditional plugin.xml includes.
>
> All that to say that we should probably just rename the plugin to 'Google
> Cloud Tools'..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/354>.
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by joaoandremartins** [comment]
There are many existing Cloud Tools already. I think most of them are being concentrated on Cloud SDK. Are we sure we won't clash with anything already existing?

If the plan is to make available every tool feature of every tool in this IntelliJ plugin, then SGTM. Sounds like it is already called Google Cloud Tools Core, so it would just be slashing "Core" from it?

**Comment by csells** [comment]
Is there an issue with “Cloud Tools for IntelliJ”?

On Jan 12, 2016, at 2:47 PM, Elliotte Rusty Harold <notifications@github.com<mailto:notifications@github.com>> wrote:

Makes sense. "Google Cloud Tools", "Google Cloud Platform Tools",
or "Google Cloud Platform Plugin"

On Tue, Jan 12, 2016 at 5:12 PM, Patrick Flynn <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Both the 'core-plugin' and the 'Google Cloud Tools Core' plugin name are
> bad names.
>
> 1) Users looking at our plugin in the IJ repo aren't going to understand
> what distinction 'core' makes, since there are no other Google Cloud Tools
> plugins.
> 2) If we eventually refactor our plugins and break them out into pieces,
> for instance 'Cloud Debugger' plugin, 'Cloud Repo' plugin, 'App Engine'
> plugin, we won't want to have to make the user reinstall all these new
> plugins. We'd rather the first install to imply the super-set of GCP
> tooling plugins, so that we can refactor it to depend on these new factored
> out plugins, and hopefully things will still work.
> 3) If we never do componentize our plugin, it's likely to stay a monolith
> and support multiple IJ SKUs through conditional plugin.xml includes.
>
> All that to say that we should probably just rename the plugin to 'Google
> Cloud Tools'..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/354>.
>



--
Elliotte Rusty Harold
elharo@macfaq.com<mailto:elharo@macfaq.com>

**Comment by patflynn** [comment]
We definitely want 'Google' in the plugin name. It's mildly redundant to
have a plugin in the IJ repo named 'for IntelliJ'.  Although funnily enough
I did find that the IJ Azure plugin is called 'Azure Toolkit for
IntelliJ'.  They are the exception though. Another strike against using the
'... for IntelliJ' qualifier, is that we also support Android Studio, and
could conceivably support more platforms in the future. The vast majority
of plugins are named for what they provide and leave IntelliJ out of their
name.

Other cloud plugins are called:

"Amazon EC2"
'Heroku integration"
"CloudFoundry integration"
"OpenShift integration"


'...Plugin' is basically non existent as a name and it also feels redundant
in a plugin repo so I vote we avoid that option.

I'm down with 'Google Cloud Tools' and Elliotte's suggestion of 'Google
Cloud Platform Tools'

**Comment by csells** [comment]
Google Cloud Tools for IntelliJ is going to be the product name in all of our docs etc. I’m OK with either “Google Cloud Tools” for the plugin or using the full name (redundancy and all : ).


On Jan 13, 2016, at 8:06 AM, Patrick Flynn <notifications@github.com<mailto:notifications@github.com>> wrote:

We definitely want 'Google' in the plugin name. It's mildly redundant to
have a plugin in the IJ repo named 'for IntelliJ'. Although funnily enough
I did find that the IJ Azure plugin is called 'Azure Toolkit for
IntelliJ'. They are the exception though. Another strike against using the
'... for IntelliJ' qualifier, is that we also support Android Studio, and
could conceivably support more platforms in the future. The vast majority
of plugins are named for what they provide and leave IntelliJ out of their
name.

Other cloud plugins are called:

"Amazon EC2"
'Heroku integration"
"CloudFoundry integration"
"OpenShift integration"


'...Plugin' is basically non existent as a name and it also feels redundant
in a plugin repo so I vote we avoid that option.

I'm down with 'Google Cloud Tools' and Elliotte's suggestion of 'Google
Cloud Platform Tools'

**Comment by patflynn** [comment]
Sounds good. 'Google Cloud Tools' will be the plugin name in the IJ repo.
 'Google Cloud Tools for IntelliJ' will be the product name everywhere
else.

**Comment by loosebazooka** [comment]
sgtm
