### ISSUE TITLE
I18n UsersListCellRenderer

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-intellij#356]
In the account plugin these user visible strings should be moved to resources:

public class UsersListCellRenderer extends JComponent implements ListCellRenderer {
  private final static String CLOUD_LABEL_TEXT = "Open Google Developers Console";
  private final static String PLAY_LABEL_TEXT = "Open Play Developer Console";
  private final static String SIGN_IN_TEXT = "<HTML> Sign in with your Google account to start <br> adding "
    + "Cloud functionality to your <br> Android applications from Android Studio. </HTML>";
  private static final String LEARN_MORE_TEXT = "Learn more";

**Comment by meltsufin** [comment]
Fixed by #547
