### ISSUE TITLE
mySyncStashCheckbox visibility issues

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/gcloud-intellij#364]
mySyncStashCheckbox needs to made invisible when appropriate in CloudAttachDialog.checkSyncStashState

**Comment by loosebazooka** [comment]
I'd probably reset all the UI properties at the top of the function and enable them when necessary

**Comment by etanshaul** [comment]
To reproduce:

1) Select a module from the debug dialog that requires sync or stash - observe the sync/stash checkbox appear
2) Select a different module that does not requie sync / stash & does not have remote repositories

Issue: the checkbox visibility is not being reset under this condition and is therefore still visible when it should not be.
