### ISSUE TITLE
Some expand icons don't work on the Variables table

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/gcloud-intellij#381]
Before and after in screenshots.

![screen shot 2016-01-20 at 4 42 07 pm](https://cloud.githubusercontent.com/assets/3290856/12463995/e3eee2b4-bf94-11e5-9c40-d8547a9b99cc.png)
![screen shot 2016-01-20 at 4 42 16 pm](https://cloud.githubusercontent.com/assets/3290856/12463996/e5febca0-bf94-11e5-93e5-ab5f7b667770.png)

Need to know if there is any data behind these objects or if this is the normal behaviour.

**Comment by loosebazooka** [comment]
before and after some change?

**Comment by joaoandremartins** [comment]
Before and after clicking on some arrows.

**Comment by elharo** [comment]
due to appengine security manager not sending private fields of system classes, WAI.
