### ISSUE TITLE
Apps built with gcloud don't contain source context

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/gcloud-intellij#383]
This is troublesome, as the Attach dialog makes use of that context to attach/not attach. We need to come up with a good strategy of handling these apps (e.g., Java MVM apps can only use gcloud).

I was able to change a project's underlying file system structure (i.e., renamed one of the folders) and still launch a debug session, which could cause unexpected issues. (e.g., #353 )

**Comment by patflynn** [comment]
Yes we're aware of this but it's being tracked by the gcloud team.
