### ISSUE TITLE
We need user docs for the cloud debugger

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#385]
ideally they should include:
- reference documentation
- an end to end tutorial

**Comment by patflynn** [comment]
Here are some notes from looking at the tutorial on gh-pages :

- The Cloud Debugger doesn't work on MVM at the moment unless it's a compat runtime and you still need to perform manual steps to ensure source context.
- IDEA CE or UE?
- if it's an AE1 example it can't use java 8
- does it have to be chrome browser?
- Exact name is Google Cloud Tools
- mention that they have to accept to install the required google account plugin
- is artifact id relevant to the deployment?
- a newer version of the sdk is available
- The current flow for setting up the git project doesn't really work. Maybe we should suggest the user fork the sample, then connect that fork to cloud repos, then checkout using IJ cloud repo integration.
- set the name of the configuration to .. anything?
- set a breakpoint: no instructions to go to the file
- how do you set a 'breakpoint'?  maybe they haven't used the IJ debugger
- useragent isn't null when I try this..
- I don't follow how you click on the request object and inspect its toString method.
- in our example it doesn't work because we're in sandboxed AE1. Why do we tell them to try and, and then tell them it won't work in the example's environment?
- The 'Run the application' section doesn't feel like it leads from the previous one. Maybe I'm missing something. What are we trying to show the user here?

**Comment by elharo** [comment]
When will the cloud debugger work on MVMs?

**Comment by patflynn** [comment]
+ludo
+erezh

If it's a custom image, the user has to configure that themselves, so it'll
never work automatically.  For the Google provided images I think it works
currently for wars but not jars.

**Comment by elharo** [comment]
Chrome browser works, but they need any browser that is not Firefox.

**Comment by patflynn** [comment]
The Cloud Debugger already works for MVM with Java and Python. It is
enabled automatically for provided images and can be enabled for customer
images.
Go and Node.java only work for GCE at the moment.

**Comment by patflynn** [comment]
Has this changed recently?  I thought I had tested the openjdk image for a
jar based deployment in late December and couldn't seem to get cloud
debugging to work.

**Comment by elharo** [comment]
I was running the cloud debugger on an MVM app a couple of weeks ago,
though I did have to do some manual config to setup the source context.

On Fri, Jan 22, 2016 at 3:59 PM, Patrick Flynn <notifications@github.com>
wrote:

> Has this changed recently? I thought I had tested the openjdk image for a
> jar based deployment in late December and couldn't seem to get cloud
> debugging to work.
>
> On Fri, Jan 22, 2016 at 2:34 PM, Erez Haba <erezh@google.com> wrote:
>
> > The Cloud Debugger already works for MVM with Java and Python. It is
> > enabled automatically for provided images and can be enabled for customer
> > images.
> > Go and Node.java only work for GCE at the moment.
> >
> > On Fri, Jan 22, 2016 at 8:33 AM, Patrick Flynn <paflynn@google.com>
> wrote:
> >
> >> +ludo
> >> +erezh
> >>
> >> If it's a custom image, the user has to configure that themselves, so
> >> it'll never work automatically. For the Google provided images I think
> it
> >> works currently for wars but not jars.
> >>
> >> On Fri, Jan 22, 2016 at 11:32 AM, Elliotte Rusty Harold <
> >> notifications@github.com> wrote:
> >>
> >>> When will the cloud debugger work on MVMs?
> >>>
> >>> —
> >>> Reply to this email directly or view it on GitHub
> >>> <
> https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/385#issuecomment-173969708
> >
> >>> .
>
> >>>
> >>
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/385#issuecomment-174045356>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com
