### ISSUE TITLE
Play console and dev console links broken

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-intellij#389]
In the "Google Login test" scenario, step 31, Try clicking on the ‘open cloud console’ and ‘open play console’ links and make sure they work, does not work. Looks like the URLs have changed.

Both end up with

URL not found

We couldn't find what you were looking for. Try one of the links below.

    Google Developers Console Home
    Google Cloud Platform
    Google Developers

at 

https://console.developers.google.com/accountsettings?pli=1
https://console.developers.google.com/accountsettings

**Comment by patflynn** [comment]
The play console link seems to still work.
