### ISSUE TITLE
IDE internal error when selecting a forbidden project

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#396]
When selecting a project to debug in the debug dialog for which the user does not have permission (an HTTP 403 is returned), the IDE reports an an "Internal IDE error has occurred":

![image](https://cloud.githubusercontent.com/assets/1735744/12620305/cd5622d8-c4e9-11e5-8ae4-630cffa59dca.png)

This should probably not be reported as an internal IDE error, and just display the error message in the dialog as usual.

**Comment by etanshaul** [comment]
Corresponding event log:

![image](https://cloud.githubusercontent.com/assets/1735744/12620398/24a49d6c-c4ea-11e5-814b-5e29ac504146.png)

**Comment by patflynn** [comment]
This is a dupe of #229

**Comment by patflynn** [comment]
@akerekes 
reopening to track this particular user flow of handling forbidden error in the attach dialog.
