### ISSUE TITLE
Display logout warning related to cloud debugger sessions only if there is at least one in progress

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-intellij#412]
When users click logout, they are presented a confirmation dialog that allows for adding messages to it. Currently the plugin will add a warning about background debug sessions always which would be weird for a user if she never touched the Cloud Debugger functionality, so let's make it conditional on having at least one debug session listening for events in the background.

This issue addresses https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/395#discussion_r51919400

**Comment by patflynn** [comment]
As long as the message doesn't imply that a session is active now I don't think this is an issue.  It's actually a feature because it  advertises the cloud debugger.

**Comment by loosebazooka** [comment]
I think that's
