### ISSUE TITLE
Removing a selected breakpoint does not clear out frames and variables

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#434]
Before:

![image](https://cloud.githubusercontent.com/assets/1735744/12956675/271a93a4-cff7-11e5-8438-05e7d2e1a9e7.png)

After clicking the "remove" button:

![image](https://cloud.githubusercontent.com/assets/1735744/12956710/426c724e-cff7-11e5-929c-b9945c3b4a9b.png)

Also happens when clicking "delete all"

**Comment by patflynn** [comment]
Was this recently introduced?

**Comment by etanshaul** [comment]
No. I checked out an old (several weeks ago) commit and it was there as well.
