### ISSUE TITLE
Managed VM deployment should have an easier path to selecting a deployable artifact

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#449]
IntelliJ's primary binary deployment model elements are 'Artifacts'.  Out of the box IJ CE comes with Jar artifacts and UE has Jar and Wars.  These are native artifacts and not generated automatically from a Maven or Gradle import.  This means the user has to manually create a corresponding IJ Artifact for whatever binaries their project is producing to be able to deploy to MVM. 

Solutions to this problem are:
1) In the MVM deployment configuration allow the user to select an arbitrary war or jar from the project files without needing an 'Artifact' in the project model.
2) Add new Jar and War artifact types available through our plugin that somehow detect the binary artifacts of a Maven or Gradle build and add them automatically to the project model.

**Comment by etanshaul** [comment]
Just to point out - IJ UE will automatically create the ear/war artifacts from a properly set up maven/gradle project which will then be available for deployment. Therefore the workflow for a UE user is pretty smooth as is.

For CE we still have to do some work to get deployable artifacts, like you suggested.

**Comment by patflynn** [comment]
You're absolutely right.  I'd love jar based projects to be just as smooth
in UE (and CE).

**Comment by etanshaul** [comment]
Does deploying a jar even make sense in this context?

**Comment by patflynn** [comment]
Yes it does.  Jar based web apps are becoming very popular these days (make
jar, not war). Check out Spring boot.
