### ISSUE TITLE
Logout from google account throws NPE

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#455]
`IntellijGoogleLoginMessageExtender.additionalLogoutMessage` needs proper guards

**Comment by patflynn** [comment]
Is this happening in our current release?  What triggers it?

**Comment by etanshaul** [comment]
Yes, its due to the way we are loading the components from the pico containter.  `ApplicationManager.getApplication().getComponent` which was returning null instead of `ServiceManager.getService`

I have a fix but @akerekes and I were quickly looking into improving the testing to cover this.

**Comment by patflynn** [comment]
If this is happening in our currently deployed release we should put out a new maintenance release with the fix ASAP.

**Comment by etanshaul** [comment]
If no one has started a release yet, I'll go ahead and start one.

**Comment by patflynn** [comment]
thanks Etan.
