### ISSUE TITLE
When backend server has changes it causes error on the client side

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-intellij#459]
When a breakpoint is set, and the user keeps a debug session listening in the background the client periodically checks the Cloud Debugger backend for changes with a hanging get using a wait token.
If the breakpoint is hit, the backend will return an HTTP 409 to the client to notify it about results being ready to query. When this 409 is received due to recent changes in how we handle errors in requests, it was also handled as error this showing an IDE error notification to the user, instead of simply suppressing it.

**Comment by patflynn** [comment]
Can we also verify what happens if we cut the network while listening?

**Comment by akerekes** [comment]
If a debug session is in progress, then no error is shown to the user, but the plugin retries to connect to the backend periodically (currently about every 0.5 sec).
If a debug session is listening in the background, then the error is caught, the user is notified via a bubble notification and the background listening is stopped.
