### ISSUE TITLE
Pull Google API dependencies from Maven

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#463]
Related to #223 

Currently these jars are manually added to the project. We should probably pull them maven; the clouddebugger API jar exists in maven central (1 minor version ahead of ours) - those that aren't in the repository should be added.

http://search.maven.org/#search%7Cga%7C1%7Cclouddebugger

**Comment by meltsufin** [comment]
Fixed by #534.
