### ISSUE TITLE
Misleading wording for continuing a background debug session 

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#480]
1) Start a debug session, and add a breakpoint
2) Click the stop icon and choose to listen in the background
3) Click the debug icon again and notice the following popup:

![image](https://cloud.githubusercontent.com/assets/1735744/13611756/1a9be916-e532-11e5-905d-48d9d0919943.png)

4) Click 'OK' on the above dialog. Notice the the state of the debug dialog now:

![image](https://cloud.githubusercontent.com/assets/1735744/13611781/32e2d192-e532-11e5-8382-fff66ed3cfb8.png)

The wording on these dialogs is inconsistent because the first one asks the user to stop the debug session, and after doing so, the next dialog asks the user to continue the session. The logic is working properly: when reopening the debug session it actually attaches a new session and uses the already existing breakpoints from the server. 

I propose that this should be a wording fix: for instance instead of "start a new session", the wording (in both cases) should could be something like "re-attach your session".

**Comment by patflynn** [comment]
why would I want to start a new session if I'm attaching to the same
project that's currently listening in the background?

**Comment by etanshaul** [comment]
that's a great question, I was wondering the same thing. Its currently the way it was set up (`CloudDebugRunner.ensureSingleDebugSession`). I'll see if this is still necessary.

**Comment by etanshaul** [comment]
After looking at it more closely, the session isn't actually destroyed: when a debug session in the background is "stopped" (after choosing "OK" in the first dialog) all that happens is the background listening is stopped. So we still only have a wording issue here.

Talking this through with @akerekes we think a good approach would be to update the wording in the first dialog to say:

"A cloud debugger session is listening in the background
Would you like to re-open the debugger and continue your session?"

**Comment by patflynn** [comment]
So the option is either reattach to existing session or start a new one and
and select a new module/version?  Is that what the UI affords?

**Comment by etanshaul** [comment]
Correct. However, the debugger dialog will currently show a "Continue Session" button for _all_ module/version regardless of which was in the background - clicking on it for a different module/version will attach a new session. This isn't ideal but it will start to get clunky if we change the button text when the user selects a different module and then do something like prompt them to kill off the other background sessions. 

Also just to clarify what is meant when I say "session": when the debugger is in the background, the IJ debug session is not live, however we maintain the state and the debug point on the server still exists.

**Comment by etanshaul** [comment]
I will open a different issue for my last comment. I think they can be thought of independently.

**Comment by etanshaul** [comment]
Closing since this is subsumed by #483
