### ISSUE TITLE
We need to update to use the latest GCP resource API

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#496]
https://cloud.google.com/resource-manager/

The current client we use for project lookup is unsupported. We need to move to the API linked above.

**Comment by meltsufin** [comment]
@patflynn Which version of the API should we be using? The one currently posted for download on the official site is v1beta1-rev12-1.21.0. I'm trying to use it, but get the error below, even after enabling it for my project. The web site does mention that "Access to this feature is currently invite-only." So, I don't know if it needs to be enabled on some higher level.

```
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Project has not enabled the API. Please use Google Developers Console to activate the 'cloudresourcemanager' API for your project.",
    "reason" : "forbidden"
  } ],
  "message" : "Project has not enabled the API. Please use Google Developers Console to activate the 'cloudresourcemanager' API for your project.",
  "status" : "PERMISSION_DENIED"
}
```
