### ISSUE TITLE
capture usage tracking in MVM deployment

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#497]

**Comment by chanseokoh** [comment]
Is this basically like collecting anonymous data about how a user uses our plugin after the user consents to send non-private data to Google? It then sounds like we will have to set an intern server to collect those data. Or, are we talking about something else?

**Comment by patflynn** [comment]
We have an existing API to collect this information.

Take a look at com.google.gct.idea.git.UploadSourceAction:114 for an
example.

**Comment by chanseokoh** [comment]
Closed by #525.
