### ISSUE TITLE
Disable pmd force override equals, hashcode

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#512]
Currently PMD forces us to override equals and hashcode even if we don't want to modify the behavior of the superclass. It suggests to have a stub override that just calls super. (Whats worse is that if you follow its suggestion it then complains that you are overriding a method that does nothing but call super). We should disable this PMD check altogether.

**Comment by chanseokoh** [comment]
Disabling a certain PMD rule can be done by modifying 'custom-pmd-ruleset.xml' in the root directory. You will need to add an 'exclude' element with the name of the rule. One example exclusion is already in the 'custom-pmd-ruleset.xml', so it should be straightforward to add another.

**Comment by etanshaul** [comment]
Correction - this was actually a findbugs warning.
