### ISSUE TITLE
Better error handling after bad MVM deploy attempt

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#515]
Currently if the user attempts to deploy to a misconfigured artifact or points to a non-existent archive, the IDE will throw an exception. The App Server window and its command line view won't give any indication that the deploy failed - it will show that the deploy was initiated, but nothing after that.

We should route this failure information to the UI so that the user is aware; and probably also prevent the exception from trickling up to the IDE.

**Comment by patflynn** [comment]
fixed by #518
