### ISSUE TITLE
move plugin to java8

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#522]

**Comment by patflynn** [comment]
AS 2.2 and IJ 2016.1 are Java 8 based. We are going to start targetting Java 8 for our plugin.

**Comment by patflynn** [comment]
On second thought I want to delay this change until after 0.9.3 release.

**Comment by etanshaul** [comment]
removing the milestone as we don't yet have plans to stop supporting IJ 15
