### ISSUE TITLE
update appengine mvm naming to 'flex'

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#524]

**Comment by etanshaul** [comment]
are we ok leaving the mvm wording internally (class names, variable names etc) or do we want it all replaced?

**Comment by patflynn** [comment]
Let's hold off on renaming for now. I think we'll likely do some renaming
when we start supporting standard deployment flows.

**Comment by loosebazooka** [comment]
Sounds like it might just make sense to do the renaming now if it isn't too much work. Easier now than later, right?

**Comment by patflynn** [comment]
OK, how about this: We rename the classes to be non specific about the
flex/standard environment. So AppEngineCloudtype, etc. That way should we
combine standard and flex into the same cloud later, we're covered, and if
we make them separate, we don't necessarily have to rename what's there
now.  Thoughts?

**Comment by etanshaul** [comment]
That makes sense to me. Unless later on we actually need separate implementations for App Engine standard vs Flex.
