### ISSUE TITLE
should we have a flags field in mvm deployment run configs?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#530]

**Comment by etanshaul** [comment]
I was looking through the available flags and this might be useful -  for instance supplying a custom version for the new deployment, or doing a local docker build.

As a side note, I noticed a `--stop-previous-version` flag which, if set (its not by default, which is odd to me), would make the need for a stop button in IJ sort of unnecessary.

**Comment by patflynn** [comment]
I think they're changing that. 

@arouzrokh

**Comment by arouzrokh** [comment]
Ethan I think the custom flag entry is a great idea. Jetbrains has a similar field where it's passed to gcloud upon deployment. Please add that ability in. 

@patflynn the changes to gcloud default behaviour doesn't break anything we do here so we can disregard that.

**Comment by etanshaul** [comment]
One approach @patflynn and I were discussing for this is rather than having a field for the user to input flags in a free-form way, we create a structured UI for them to use. For example, a checkbox to enable/disable auto-scaling and we internally set the corresponding flags. 

The two approaches aren't mutually exclusive though: we probably wouldn't want structured UI corresponding to every possible flag gcloud can take.

**Comment by arouzrokh** [comment]
Correct. We can actually have the flag populate the content in the free-form and, when free-form change is activated, we deactivate the structured UI elements. 
but, MVP would be just free-form for the sake of time and functionality.

**Comment by patflynn** [comment]
@arouzrokh do you know why module name isn't something we can pass as a flag to gcloud deploy?

**Comment by etanshaul** [comment]
Maybe we should revisit this now for the 1.0 milestone. 

One flag I think is important is the 'promote' flag which we currently hardcode to true.

**Comment by patflynn** [comment]
yes definitely.

**Comment by etanshaul** [comment]
Can we think of any other flags that are critical? The two I can think of are:

- --promote
- --stop-previous-version

I imagine these as checkboxes underneath the version field.

**Comment by patflynn** [comment]
+1
