### ISSUE TITLE
Cloud SDK path selection should allow selecting root SDK dir

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-intellij#535]
Currently, when configuring the Google Cloud SDK for Appengine flexible environment, the user must select the bin subdirectory of the SDK installation path. This may be counter to the expectation of the users that selecting the SDK root directory should work.

![screenshot from 2016-03-24 11 53 55](https://cloud.githubusercontent.com/assets/17732492/14022647/1eabcd82-f1b7-11e5-95e5-3e7115a68ac9.png)

**Comment by patflynn** [comment]
+1. This needs to be fixed.
