### ISSUE TITLE
App Engine deployment should set the gcloud metrics environment for server side analytics

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#542]
CLOUDSDK_METRICS_ENVIRONMENT

**Comment by meltsufin** [comment]
What should be the value?

**Comment by patflynn** [comment]
@vilasj

Vilas should we use a specific name format for this variable?

**Comment by vilasj** [comment]
No specific suggestion here. Just a very short ascii string that clearly identifies your tool/environment. For comparison, here are a couple we currently use:  'devshell', 'GCE'.

**Comment by meltsufin** [comment]
How about CT4IJ?

**Comment by vilasj** [comment]
SGTM

**Comment by patflynn** [comment]
Is there a character limit?

**Comment by vilasj** [comment]
We do not impose any limit. So the limits here are the max length of an env variable, and HTTP user-agent. But I would recommend not testing those :) As short as possible without looking cryptic is good. Note that you will be using this string repeatedly in queries/analysis that you perform in the future.

**Comment by patflynn** [comment]
Perhaps just 'gcloud-intellij', as this is the application name prefix
we're putting in our user-agent for API requests.

**Comment by vilasj** [comment]
SG, that would be appropriate and consistent.
