### ISSUE TITLE
What happens if we try to deploy with an old version of gcloud?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#543]
Ideally the user would be notified to update if their version of gcloud does not support credential_file_override flag

**Comment by meltsufin** [comment]
Deployment fails with 

> ERROR: gcloud crashed (AuthPermanentFail): Refresh token is invalid.

**Version used**: Google Cloud SDK 101.0.0

**Console output**:
...
Beginning deployment...
ERROR: gcloud crashed (AuthPermanentFail): Refresh token is invalid.
 
If you would like to report this issue, please run the following command:
   gcloud feedback
Failed to deploy 'userSpecifiedSource': Deployment failed with exit code: 1
...
