### ISSUE TITLE
App Engine server type allows to connect even when logged out

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-intellij#552]
Steps to reproduce:

1. Set up the App Engine Flexible Environment server.
2. Logout from GCP using the account icon on the toolbar.
3. Click "Connect" button on the App Engine Flexible Environment Server and see it succeed.

The same can be said about the disconnect button.

The problem is that after this "successful connection", the deployment action fails with:

> Failed to deploy 'userSpecifiedSource': You must be logged in to deploy."

**Comment by etanshaul** [comment]
I don't think this "connect" feature does anything useful for us outside the context of a deploy. Deploying implicitly does a connect and requires the user to be logged in. Maybe we move the Auth checking to the connect callback instead?

**Comment by patflynn** [comment]
I thought we had disabled 'connect'.

**Comment by meltsufin** [comment]
I think we should just duplicate the authentication checking in connect().
Alternatively, just hide the connect and disconnect buttons if IntelliJ allows that.

**Comment by patflynn** [comment]
Where do you see connection buttons?  I'm not seeing any.

**Comment by meltsufin** [comment]
The play button here:
![screenshot from 2016-03-29 13 24 09](https://cloud.githubusercontent.com/assets/17732492/14117185/8edd5f3c-f5b1-11e5-9dcd-a3e1485e477c.png)

**Comment by etanshaul** [comment]
+1 for hiding the button if possible. Its a function that doesn't really map onto our desired workflow.

**Comment by patflynn** [comment]
Yeah. 'Connect' as a concept seems pretty meaningless for most usecases I
can think of.

**Comment by meltsufin** [comment]
I can see how 'Connect' can actually mean 'login', and 'Disconnect' mean 'logout'. It would especially make sense for someone who's building a plugin that only provides a cloud application server.
So, if we wanted to make use of these buttons, it might make sense to synchronize them with the user auth status of the account plugin.

**Comment by patflynn** [comment]
I don't want to do that at this point. I think it would be surprising
behavior to Google logout when they disconnect from a specific 'cloud
server'.

**Comment by meltsufin** [comment]
How about "disconnect" automatically when login status changes to logged out, but still keep the disconnect action as no-op?
