### ISSUE TITLE
Should MVM deployment allow a custom app.yaml without selecting a custom Dockerfile?

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#554]
Or vice versa.

Currently, if the user attempts this, the deploy will fail with an exception (filenotfound for the config file that was not specified).

**Comment by etanshaul** [comment]
One option is to allow the user to select one of the custom configs but not the other (and fall back on the default option for the one that was not selected).

The other option is to show an error message - i.e. if the user selects 'Custom' then he must select _both_ and app.yaml and a Dockerfile.

I'm in favor of the later option.

**Comment by chanseokoh** [comment]
I like the later option. There is already a 'Generate...' button for each of the config files, and clicking it will auto-fill the input text box.

**Comment by patflynn** [comment]
Let's just not validate the app.yaml and Dockerfile configuration.  If they
screwed up gcloud can complain.  I'd like to stay as dumb as possible for
now until the surface and the workflow solidify a little bit.
