### ISSUE TITLE
Set clientVersion on Cloud Debugger Debuggee requests

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#558]
client version string should be "google.com/intellij/v{currentPluginVersion}".

**Comment by chanseokoh** [comment]
Seems like we can simply call 'setClientVersion()' before every 'execute()'.

**Comment by meltsufin** [comment]
This doesn't seem ideal because we have to make this call to setClientVersion() in multiple places, but I don't see an alternative in the API.

**Comment by patflynn** [comment]
Yeah.  Unfortunately for now I don't see a way around this.
