### ISSUE TITLE
Customer Dockerfile generation ('Generate...' button) error

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-intellij#560]
Clicking the 'Generate...' button in the Flex deploy dialog and specifying a directory spits out an error:

[  57172]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'deployPackage' of com/google/gct/idea/appengine/cloud/DeploymentArtifactType.typeForPath must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'deployPackage' of com/google/gct/idea/appengine/cloud/DeploymentArtifactType.typeForPath must not be null
	at com.google.gct.idea.appengine.cloud.DeploymentArtifactType.typeForPath(DeploymentArtifactType.java)

**Comment by patflynn** [comment]
can you fix this Chanseok?

**Comment by chanseokoh** [comment]
I'll do it.

**Comment by etanshaul** [comment]
Ah, this is because its currently possible to generate a Dockerfile before selecting a deployment source. The Dockerfile relies on the deployment source being chosen (e.g. jar or war).

**Comment by chanseokoh** [comment]
Interesting. The app.yaml generation works fine though.

**Comment by etanshaul** [comment]
right, because the app.yaml doesn't care about the deployment source

**Comment by etanshaul** [comment]
I suggest you add a new error message when the user attempts to generate a Dockerfile before having set the deployment source. Something like:

"Please select a deployment source before generating a Dockerfile."

**Comment by chanseokoh** [comment]
I cannot throw a ConfigurationException from an ActionListener. What could be the way?

**Comment by etanshaul** [comment]
What is the error you are seeing?

**Comment by chanseokoh** [comment]
Seems like I need to handle this error inside 'GenerateConfigActionListener.actionPerformed()', but not sure how I can actually propagate the error message to the dialog there.

**Comment by chanseokoh** [comment]
I guess I will create and pop-up an error message dialog rather than using the ConfigurationException mechanism.

**Comment by patflynn** [comment]
Would an option be to disable the app configuration if no artifact has been
selected for user selected jar/war?

**Comment by etanshaul** [comment]
This issue goes a little deeper: if the user selects a filesystem deployment source, the Dockerfile generation doesn't work either. It attempts to call `deploymentSource.getFile()` but there is no file set for this custom deployment source type since the file gets created later (when the user browses to one).

**Comment by etanshaul** [comment]
What I just said may warrant a separate issue.

**Comment by chanseokoh** [comment]
Let me try Partrick's option first.

**Comment by etanshaul** [comment]
Ok. But I don't think that will fix my last comment. I'll open an issue for that to make sure.

**Comment by etanshaul** [comment]
@chanseokoh check out #565 to make sure it doesn't conflict with what you are working on. I won't merge it in until you fix this one.

**Comment by chanseokoh** [comment]
Please merge it first.

**Comment by chanseokoh** [comment]
I think an error dialog is better here. Showing/hiding based on whether the current file name extension is .jar or .war doesn't seem like it will work reliable. Unfortunately, I'm a little bit stuck displaying an error dialog. Can't figure out why a dialog does not show up. The Dialog class is derived from JDialog, and I am just instantiating with 'new NoJarOrErrorDialog'.
