### ISSUE TITLE
Allow users to enter custom versions and module name for flex deployments

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#572]

**Comment by etanshaul** [comment]
Noting this behavior since its relevant:

When deploying with a specified version that matches an already deployed version, gcloud does _not_ error out. Rather it overrides the existing version of the application.

**Comment by patflynn** [comment]
Well that's interesting.

@arouzrokh.

**Comment by patflynn** [comment]
I'd want us to do this as one PR.  I think having one without the other will be weird.

**Comment by patflynn** [comment]
It could be nice to get this in for our 0.9.3-beta. I'd be happy to delay a day to support this level of configuration

**Comment by etanshaul** [comment]
Note: it appears that flex deployments with custom module names (as flags) is not supported. Therefore, this issue will focus on version only.
