### ISSUE TITLE
Do we want to lower the verbosity level of flex deploy console output?

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#573]
And is it possible to do so? 

Here is a sample of the output:

![image](https://cloud.githubusercontent.com/assets/1735744/14211761/c862de5a-f7fd-11e5-9079-093bd3b872d1.png)

I tried adjusting the --verbosity flag for gcloud but wasn't able to adjust the output.

**Comment by patflynn** [comment]
For now let's follow gcloud's lead.  If verbosity controls for deployment are introduced, we can potentially expose that in our UI.
