### ISSUE TITLE
Error handling for config file generation ('Generate...' button in Flex deploy dialog)

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-intellij#574]
Errors are currently not well-handled.

- If a user just hit enter or click 'Ok' (will be 'Generate' after #570) in the directory selection window, it will create a file in the following directory. (The confirm dialog below will be after #570.)

![empty_dir](https://cloud.githubusercontent.com/assets/10523105/14212168/8c941b4e-f7ff-11e5-9ea4-76be6b56e18d.png)

- If a user provides a directory with no write permission (e.g., '/' root directory), nothings seems to happen except the following red error pop-up appears at the top-right corner. Seems like this is due to throwing RuntimeError whenever any IOException occurs.

> IDE internal error occurred.
> Click to see details and submit a bug report.

**Comment by patflynn** [comment]
It seems like there are two issues.   
1) That default is pretty unexpected.  If  the user hits OK without specifying a target directory that should be a validation error.

2) If there is a file related error generating the file we should show a generic error indicating that there was a problem generating the file.
