### ISSUE TITLE
Generated app.yaml and Dockerfile should have a sensible default target directory

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#575]
assuming it's a Maven shaped project structure, the app.yaml should go in:
src/main/appengine

and the Dockerfile should go in:
src/main/docker

**Comment by meltsufin** [comment]
I think resources usually go into src/main/resources in Maven and become part of the classpath. Is there any reason not to follow that convention here?

**Comment by patflynn** [comment]
app.yaml and Dockerfile are not project resources. They are build and
deploy inputs and do not appear in the project's classpath.
