### ISSUE TITLE
Flex redeploy button should not generate a new version

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#576]
Instead, it should override the version that was just deployed.

**Comment by chanseokoh** [comment]
Hmm. But gcloud also generates a new version all the time. It seems also tricky to define if this deploy is a re-deploy or a new deploy. Users can change deploy config settings in many ways, and what could be considered a new deploy? If a user selects a different artifact? If app.yaml changes? And, what if a user does not want to override the last deploy but want to explicitly deploy a new one?

**Comment by etanshaul** [comment]
Good point - I was talking only about changing the functionality of the "redeploy" button (not the "deploy" button). But it is possible for the user to edit the config and then hit "redeploy" like you said. In this case "redeploy" does act like a new deploy.

**Comment by etanshaul** [comment]
I agree with @chanseokoh point. How about closing this one for now?

**Comment by etanshaul** [comment]
Closing this due to the behavior of the redeploy button.
