### ISSUE TITLE
Browse for app.yaml location dialog title has strange capitalization. 'Browse for Your App.Yaml Location'

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#597]
![appyaml](https://cloud.githubusercontent.com/assets/7862557/14317328/c0ec3b0e-fbd5-11e5-9932-6a733352e2cb.PNG)

**Comment by chanseokoh** [comment]
Where and when are you seeing this? When clicking the 'Generate' button after selecting a directory in a currently open project? I wonder if this is an Idea 2016 thing.

**Comment by patflynn** [comment]
Woops. No this heading is wrong. It should be when you select browse for an existing app.yaml location.

**Comment by patflynn** [comment]
It should be 'Browse for your app.yaml location'
