### ISSUE TITLE
It would be cool to configure mvn install or gradle build as a pre deploy step automatically for app engine deployment

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#600]
If a project is maven or gradle, it could be cool to automatically add producing the project artifacts as a prequesite of deployment.

**Comment by etanshaul** [comment]
👍 

Just adding a note that if IJ already created an artifact (if UE and it created a war artifact) then this isn't needed. This would handle the cases of jar's (CE and UE) and war's (for CE).

One approach could be, when the project has a configured Maven / Grade facet, to create a new custom deployment source type (MavenDeploymentSourceType for example) which automatically adds the pre deploy step and is aware of the target archive.
