### ISSUE TITLE
Corrupted saved credentials cause false logged in state

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-intellij#601]
The error I get in the IntelliJ Event Log is:

> IllegalArgumentException: Argument for @NotNull parameter 'userEmail' of com/google/cloud/tools/intellij/login/CredentialedUserRoster.setActiveUser must not be null

It appears that the Account Plugin saved a corrupted authentication state where everything is null except for the refreshToken. The end result is that the account plugin thinks the user is logged in, but it causes failures because it doesn't have all of the needed user information.

**Comment by meltsufin** [comment]
Deleting the `prefs.xml` file in `~/.java/.userPrefs/com/google/gct/login/` directory resolves the issue.

For reference here are the original corrupted file before deletion and then the new one created after logging successfully again.

Corrupted file:
```XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="credentials_email_user@email.com" value="user@email.com"/>
  <entry key="credentials_refresh_token" value="[hidden]"/>
  <entry key="credentials_refresh_token_user@email.com" value="[hidden]"/>
  <entry key="oauth_scopes" value="https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.edit https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud_debugger https://www.googleapis.com/auth/projecthosting https://www.googleapis.com/auth/userinfo#email"/>
  <entry key="oauth_scopes_user@email.com" value="https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.edit https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud_debugger https://www.googleapis.com/auth/projecthosting https://www.googleapis.com/auth/userinfo#email"/>
</map>
```

Good file:
```XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="all_users" value="user@email.com"/>
  <entry key="credentials_email_user@email.com" value="user@email.com"/>
  <entry key="credentials_refresh_token_user@email.com" value="[hidden]"/>
  <entry key="oauth_scopes_user@email.com" value="https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.edit https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud_debugger https://www.googleapis.com/auth/projecthosting https://www.googleapis.com/auth/userinfo#email"/>
</map>
```

**Comment by patflynn** [comment]
I've' nevers seen this before. Do you know how you got into this state?

**Comment by meltsufin** [comment]
I'm not exactly sure how I got into this state, but it happened while I was working on #577 and frequently closing and reopening the project during or after cloud deployment.

**Comment by patflynn** [comment]
@meltsufin can you dig into this?  I'd like to understand the potential impact. If it's likely to be seen by users we'll need to fix this for the 0.9.4 release.

**Comment by meltsufin** [comment]
:ok:

**Comment by Bazarov47** [comment]
> Deleting the `prefs.xml` file in `~/.java/.userPrefs/com/google/gct/login/` directory resolves the issue.
> 
> For reference here are the original corrupted file before deletion and then the new one created after logging successfully again.
> 
> Corrupted file:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> <!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
> <map MAP_XML_VERSION="1.0">
>   <entry key="credentials_email_user@email.com" value="user@email.com"/>
>   <entry key="credentials_refresh_token" value="[hidden]"/>
>   <entry key="credentials_refresh_token_user@email.com" value="[hidden]"/>
>   <entry key="oauth_scopes" value="https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.edit https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud_debugger https://www.googleapis.com/auth/projecthosting https://www.googleapis.com/auth/userinfo#email"/>
>   <entry key="oauth_scopes_user@email.com" value="https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.edit https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud_debugger https://www.googleapis.com/auth/projecthosting https://www.googleapis.com/auth/userinfo#email"/>
> </map>
> ```
> 
> Good file:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> <!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
> <map MAP_XML_VERSION="1.0">
>   <entry key="all_users" value="user@email.com"/>
>   <entry key="credentials_email_user@email.com" value="user@email.com"/>
>   <entry key="credentials_refresh_token_user@email.com" value="[hidden]"/>
>   <entry key="oauth_scopes_user@email.com" value="https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.edit https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud_debugger https://www.googleapis.com/auth/projecthosting https://www.googleapis.com/auth/userinfo#email"/>
> </map>
> ```

@meltsufin 
Where to find this file in Windows 10?

**Comment by etanshaul** [comment]
@Bazarov47 what version of Cloud Code are you using?

A few releases ago we updated our login logic to migrate away from a deprecated login endpoint. I wonder if that was part of the problem. (the latest version of Cloud Code is 20.1.3; with 20.2.1 coming out in the next day or two).

But to answer your question to try and unbock, on windows this may help you locate the directory:
https://stackoverflow.com/questions/4947555/where-are-the-java-preferences-stored-in-windows-7

**Comment by Bazarov47** [comment]
@etanshaul the latest updated version resolved the issue.
Thank you

**Comment by etanshaul** [comment]
great! thanks @Bazarov47
