### ISSUE TITLE
Logger.error() for failures that are not bugs

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-intellij#605]
Our plugin often uses Logger.error() when there are failures but not bugs. For example, if 'gcloud deploy' fails with an exit code other than 0, Logger.error() will cause a small red popup saying something like 'IDE internal error occurred. Please file a bug.' The logged error can also be accessible in the event log pane. If we click the logged event, a dialog below appears where there is a button saying 'Report to Google Cloud Platform':

![report_bug](https://cloud.githubusercontent.com/assets/10523105/14328202/ac2ad65c-fc03-11e5-8203-3d172585c8ee.png)

We need to check for all the usage of Logger.error() and use it only when it is truly a bug of our plugin.

**Comment by patflynn** [comment]
Yes this is an issue. It would be nice to have analytics on how often failures occurred. But many errors will be of a transient nature that we can't control and shouldn't be reported as plugin bugs.

**Comment by chanseokoh** [comment]
Adding a note: an non-zero exit code seems to be returned whenever a deployment failed for whatever reason, for example, when a user provided an unacceptable version name (e.g., special characters). Our general policy is to delegate validation to gcloud and have it deal with logic errors, so we need to think about whether we want to have analytics like in this case where there can be a lot of noises.

**Comment by chanseokoh** [comment]
This also happens when throwing RuntimeException for these kinds of failures, which we currently do in many places.

I wonder if we can have a consensus about a nice and uniform way of informing failures to users, although it should depend on contexts. Event logs seem to be a good way for a concurrent task, but it is weird that Logger.error() actually means IDE/plugin bugs.

**Comment by chanseokoh** [comment]
Throwing an exception seems really convenient, because often we want to get out of anywhere. I wonder if there is a suitable exception we can throw that Intellij will handle nicely to show our custom error message to users.

**Comment by chanseokoh** [comment]
Anyway, @etanshaul may have different opinions about these RuntimeExceptions and Logger.error() behaviors, so we should discuss!

**Comment by patflynn** [comment]
logging error is an effective way to trigger error reporting. So IMO it's
sensible to use it if you've anticipated a problem that would be a bug
you'd like reported. Blowing up with an unhandled exception has the same
effect, but is more likely to be the result of something completely
unanticipated.

For errors that are not plugin bugs and that the user can address, we
should definitely not be using log.error or throwing uncaught exceptions.

**Comment by etanshaul** [comment]
agreed. For errors that are not bugs (deployment config issues for examples) I think a sensible solution is to replace log.error with log.info. It really is an information message in this case, not an error (or even a warning.

**Comment by loosebazooka** [comment]
log.warn?

**Comment by patflynn** [comment]
Chanseok, have you started on this?  If not I can pick it up.

**Comment by chanseokoh** [comment]
Haven't started it yet, sorry. I think you can make better decisions on these cases, so you can go ahead.

**Comment by patflynn** [comment]
no prob. thanks.
