### ISSUE TITLE
'Add User' followed with 'Deny' breaks Account Plugin UI

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-intellij#606]
Steps taken:

1. Login to Google Cloud using the toolbar icon.
1. In the browser, 'Allow'
1. Click the account toolbar icon again and select "Add Account"
1. In the browser, 'Deny'

Observe that the toolbar icon has changed to logged out state and is now gray. When you click it, you still see your logged in user from before, but now the "Sign Out" button is disabled. The plugin is effectively tricked into thinking that the user has logged out.

**Comment by chanseokoh** [comment]
#647 fixed this issue but was not auto-closing.
