### ISSUE TITLE
'gcloud' is now auto-generating app.yaml and Dockerfile if not present - require them for custom deployments

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-intellij#607]
Check it out. Run the 'gcloud app deploy' in a directory where there is only one war. If either one or both of them does not exist, it will create them.

We don't need to manually copy our templates.

**Comment by patflynn** [comment]
yeah we know. Unfortunately the tool generated configs are not ready to be used for our usecase yet.  Feel free to ask me about it offline.

**Comment by chanseokoh** [comment]
So I have a question. If we select 'custom' deployment and leave either app.yaml or Dockerfile field empty and deploy, we will no copy our templates because it is a custom deployment. In this case, gcloud will auto-generate them during deployment. Is this okay and behavior intended?

**Comment by patflynn** [comment]
@etanshaul I believe we made it a validation error not to set these fields in custom mode.

**Comment by chanseokoh** [comment]
You can leave them blank now. Perhaps we should prevent it.

**Comment by etanshaul** [comment]
@patflynn actually the opposite - we decided to let it pass through to gcloud to do the validation. Maybe you're thinking about the custom version input (in which case we _do_ require something to be input).

**Comment by patflynn** [comment]
ah, I think that was a mistake. when the user selects custom, we should require that an app.yaml is specified for now. This is because of a problem with the generated gcloud configs that's best discussed offline.

**Comment by patflynn** [comment]
also require Dockerfile.

**Comment by etanshaul** [comment]
lets use this issue to require the user to enter a Dockerfile and app.yaml when selecting custom deployment
