### ISSUE TITLE
It should be easier to discover our App Engine deployment support

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#612]
One option would be to have a 'Deploy to App Engine flexible environment' action in the tool bar, that configures a cloud deployment for the user.

**Comment by etanshaul** [comment]
@patflynn Can you explain what you had in mind here? The title mentions support, but the the description talks about a new toolbar action.

**Comment by patflynn** [comment]
our plugin supports AE flex environment deployment, but unless you've gone to settings -> clouds -> and created a cloud of the type we provide, you will not see our flex environment in the list of available deployment run configurations.  One way that Jetbrains improves the visibility of their App Engine cloud type is by including an 'upload to app engine' item in the tools menu.  What this issue is saying is that we should consider doing something similar.
