### ISSUE TITLE
Widening generated config file destination modal should widen the path text field

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-intellij#616]
![destfolder](https://cloud.githubusercontent.com/assets/17732492/14394394/1322a046-fd9a-11e5-945f-7fd304eb07a4.png)

**Comment by chanseokoh** [comment]
You are testing this on my branch (#614), aren't you? I'll fix this too.

**Comment by meltsufin** [comment]
Oh my bad, I didn't realize this wasn't in master.

**Comment by chanseokoh** [comment]
This is fixed in #614.
