### ISSUE TITLE
Our App Engine deployment run config should allow the selection of App Engine standard modules as deployment sources

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#665]
IntelliJ Ultimate has built in App Engine support, which handles build and staging of modules with the App Engine facet.  Our deployment UI should allow selecting an IJ App Engine module as a deployment source.

**Comment by etanshaul** [comment]
I wanted to get some early discussion on this and share a feel for how this might work. Here is a rough outline of what one option could look like:

Background note: IJ App Engine deployment support works off of exploded war Artifact types.

_Showing all of our current deployment source options plus a new exploded war type:_
![image](https://cloud.githubusercontent.com/assets/1735744/14989887/137180e8-1128-11e6-84ce-189b727d9088.png)


_File deployment source - not that the environment is "Flexible" and the Configuration (which applies to Flex env is enabled:_
![image](https://cloud.githubusercontent.com/assets/1735744/14989945/6a24753a-1128-11e6-958a-a3cc5dd92c6c.png)

_Exploded war source (module has been validated to have an App Engine facet). Note the environment is "Standard" and there is no configuration selector):_
![image](https://cloud.githubusercontent.com/assets/1735744/14989995/ae80a384-1128-11e6-948f-c04f25b71758.png)


Another way I can see this working is that when the user specifies the target environment initially when creating the cloud server. Then, in the deployment window, we only show the deployment sources that are applicable to that cloud. For instance, if "standard" was selected, then only the exploded war artifact (and perhaps even the Maven source) would be shown.

**Comment by chanseokoh** [comment]
Or, one could select standard/flexible from the 'Server:' drop-down (above the 'Deployment:' drop-down).

**Comment by etanshaul** [comment]
The contents of the server dropdown are fixed by the cloud configurations that the user created. If the user creates 2 clouds, one standard and one flex (per my alternative suggestion), then what you are saying would effectively be the same as my alternative suggestion.

**Comment by patflynn** [comment]
One thing that's been on my list of things to do, is consider at this point
whether some of this configuration might not belong in a module level facet
rather than in the deployment runtime.

It's conceivable for instance that the app.yaml and Dockerfile could be
part of a new App Engine facet.  It's actually kind of murky what's module
config and what's deployment config.

I'm making this shit up on the spot, but you could have something like:
if it's a plain old standard app, it just has the Jetbrains AE facet and we
support deployment from it with the 'standard' labeling as in Etan's
screenshots
if it's a standard app with env flex in the appengine-web.xml we add our
flex facet (in addition to the JB AE facet) to it which supports Dockerfile
configuration, and for deployment we label it as flex
if it's a flex app with an app.yaml we add our facet and deploy it as above.

Some of the aforementioned murkiness could be addressed by allowing the
user to override some config (app.yaml and Dockerfile for instance), in the
deploy step. Kind of the way we do now, except they'd be pre-configured
from the facet.

I haven't really though this through, so I'm not pushing for this, but it's
an option to think about.

**Comment by etanshaul** [comment]
Interesting. Some things like the cloud sdk path could definitely be considered module level config. In my mind, things that are both module related _and_ auto-configurable could be moved to a facet since these are usually configured automatically based on the project structure (we can still provide the option to override them like you said).

I will think about this idea more. One of the things I am not sure of with this approach is how we would handle projects that have no AE facets. Take a plain maven project for instance: currently we can deploy this to flex using one of several avenues. I don't know if it makes sense to nail our facet to a project like this just because our plugin is installed.

**Comment by patflynn** [comment]
Agreed.

The user would have to manually add the facet to that kind of project.
Ideally they could still deploy that kind of project without it though :)..
I know, it's messy.
