### ISSUE TITLE
Deployment settings are lost permanently when changing a deployment source and clicking 'Apply' or 'Ok'

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-intellij#679]
Steps to reproduce:

1. Create a deploy configuration. Provide some valid settings, and close the config window.
2. Open the config window again.
3. Change a deployment source (e.g., from Maven source to file system source).
 - At this point, all settings will be reset. However, if we click 'Cancel', they values will be restored when we open the config window later.
4. Click 'Ok' or 'Apply'. This will trigger validation error. Click 'Cancel' to close the window.
5. Open the window again. Deployment source selection has been changed, and all the settings are lost.

**Comment by etanshaul** [comment]
I just tested this out. I think most of this is as expected. The only issue is in steps 4, 5:

Clicking 'ok' or 'apply' with a validation error should not save any settings. Therefore, after clicking 'cancel' step 5 should reload the settings as they were prior to click 'ok'. I will look into this.

**Comment by chanseokoh** [comment]
Thanks. I also have an idea for the issue in the step 3. If there is any setting a user entered and saved, we show a confirm dialog saying something like "Your current settings will be cleared when you change a deployment source."

**Comment by etanshaul** [comment]
I have mixed feelings about that: the user can always click cancel to and re-open the dialog to restore the settings after changing the deployment source.  Regardless, from an implementation perspective this may be tricky - what's actually happening is that a new instance of the UI editor is created when a new deployment source is selected and I don't think the platform gives us a way to hook onto the change event.

**Comment by chanseokoh** [comment]
Yeah, this really seems tricky from the implementation point anyway.
