### ISSUE TITLE
Reintroduce ability to stop running deploy process

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#687]
See #674 

This got lost in refactoring of app-tools common lib.

**Comment by chanseokoh** [comment]
I have a PR for this. However, I think the refactored version of the app-tools common lib should first be deployed to the Maven Central before my PR can be merged.

**Comment by etanshaul** [comment]
Yea we should wait to merge it, but if you want you can go ahead and push the PR so we can start reviewing (travis will fail for now, but thats ok).

**Comment by meltsufin** [comment]
I don't think we have introduced any breaking changes to the tools lib since the last push to central. We can push the latest again, if you need.

**Comment by etanshaul** [comment]
Yes, that would be great.
