### ISSUE TITLE
Lack of hi DPI icons looks bad on retina and 4k displays.

### ISSUE THREAD

**Issue by bamapookie** [GoogleCloudPlatform/gcloud-intellij#706]
The snapshot icon in the editor gutter (line 31 in the screenshot) is extremely small, and in the debugger tab, the icons are pixelated.  See the attached screenshot.

<img width="190" alt="screen shot 2016-06-01 at 8 51 52 am" src="https://cloud.githubusercontent.com/assets/1924926/15710273/4a33116c-27d7-11e6-9c80-c924fed3c1ef.png">

**Comment by patflynn** [comment]
I've created a new tracker bug for all our image resources related to this: #707 

Thanks for bringing this to our attention.
