### ISSUE TITLE
incorrect copyright header

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#712]
We should be using the Google copyright header for new files in this project and not the AOSP copyright header.

s/
Copyright (C) 2016 The Android Open Source Project
/
Copyright 2016 Google Inc. All Rights Reserved.
/

**Comment by meltsufin** [comment]
You may also consider adding copyright header checking using checkstyle like we did in the Maven plugin: GoogleCloudPlatform/app-maven-plugin/pull/17

**Comment by etanshaul** [comment]
fixed by #715
