### ISSUE TITLE
Changing the deployment source during app engine deployment resets the selected project

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#722]
steps to reproduce:

1) Create a new App Engine (Beta) deployment run config
2) Select a module or artifact for deployment
3) Select your project
4) Changed the selected module or artifact
5) observe that the selected project has been reset

expected behavior:
- changing the deployment source doesn't change the target project

**Comment by chanseokoh** [comment]
@etanshaul and I had a discussion about this #679. It's not just the project, but every setting is cleared. The story doesn't seem simple. @etanshaul could provide some more context on this.

BTW, clicking on 'Cancel' will probably restore the previous settings. There might still exist some subtle problem.

**Comment by patflynn** [comment]
duplicate of #679

**Comment by etanshaul** [comment]
The reason the project is reset (along with the rest of the settings) is that, as part of the framework, changing deployment source re-instantiates the editor window with a clean configuration.
