### ISSUE TITLE
Cloud repo source import fails 

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#736]
Steps to Reproduce:
1. Create a new Project, accepting all the defaults
2. Log in with a non @google.com account (make sure you’re on Googleguest WiFi).
3. Select VCS -> Import into Version Control -> Upload Project to Google Cloud
4. Select a cloud project that has no existing sources, or create a new one
5. Click Upload

Observe:
"Fetch Failed'
"Failed to Fetch Remote Origin"

No error is logged

**Comment by patflynn** [comment]
I think this is caused by the new multiple repository model for cloud repos.  There doesn't appear to be a repo by default anymore.  If I create a new project with a repo named 'default', the upload works.

**Comment by patflynn** [comment]
A fix for this will need to be patched into Android Studio

**Comment by patflynn** [comment]
We should also make sure we log errors when cloud repo actions fail.

**Comment by etanshaul** [comment]
This has been fixed on the backend so no change is needed on the plugin.

I am leaving this open however so that we can improve our error logging.

**Comment by patflynn** [comment]
I'll create a new issue for the error logging.
