### ISSUE TITLE
Google cloud tool-cloud not locate a remote repo

### ISSUE THREAD

**Issue by xiao25** [GoogleCloudPlatform/gcloud-intellij#742]
It might be a question, but after I choose to clone my google cloud remote project into a Intellij new project, I faced the "Cloud not locate a remote repo" error message.  The steps I tried as follow:

VCS -> check out from version control ->  Google cloud -> my cloud project 
However, after I set up a cloud debugger, it keeps alert "cloud not locate a remote repo" and fail to attach/hit any snapshot. 

Pls help me on this.

**Comment by patflynn** [comment]
@xiao25 Hi Xiao, 

Thanks for your bug report.  Just to confirm:  Do you have a repository checked into your cloud project?  If so, what is it called?  

There's been a recent change to Google Cloud Repositories that allows the creation of many within one project with user-specified names. Unfortunately our plugin does not support this and still expects to use a repository named 'default' in your project.   

We'll be fixing this ASAP. Related to #736

**Comment by patflynn** [comment]
This has been fixed by the cloud repo team.
