### ISSUE TITLE
Only using new plugin...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/gcloud-intellij#769]
Create a new project...

App Engine isn't listed as an option anymore.   This seems like a deficit.

**Comment by etanshaul** [comment]
@lesv thanks for reporting. I assume you are referring to the new project generation wizard. Did you select Java (on the left panel)? Also are you using Ultimate Edition (this feature is not available in Community Edition)?

**Comment by lesv** [comment]
Yep - once I turned off the Intellij plugin, I was left w/o the option.  (ie. it's not in ours).

**Comment by etanshaul** [comment]
@lesv makes sense. I will close this issue then sense its currently working as expected. Like I mentioned, this will soon be available in our plugin once things get merged in.
