### ISSUE TITLE
Investigate potential breaking API changes in IJ EAP 2016.2

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#772]
When I target release candidate 2016.2 EAP:

ideaVersion = IU-162.1120.6 ([see here](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.2+EAP) for the build #'s)

I get compilation errors. For example: `BreakpointConfigurationPanel:247`

It looks like for that instance `WatchRootNode#getAllChildren` was removed in this EAP.

**Comment by aslo** [comment]
This is now complete. There were a few breaking changes, and some more subtle behavior changes that broke a few of our tests. I've created the [`162`](https://github.com/GoogleCloudPlatform/gcloud-intellij/tree/162) branch to hold our code that's compatible with the 162.* releases.
