### ISSUE TITLE
Update AE standard method blacklist to use a whitelist

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#784]
The code that performs inspections for disallowed java calls (shows red squiggly lines in the IDE) is using a blacklist of a few methods. We should look into instead using the official whitelist that AE uses so that users don't mistakenly think their code will deploy when it won't.

https://cloud.google.com/appengine/docs/java/jrewhitelist

**Comment by elharo** [comment]
We may want to move this into app-tools-lib-for-java since Eclipse does this too. See https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.whitelist/src/com/google/cloud/tools/eclipse/appengine/whitelist/AppEngineJreWhitelist.java

**Comment by etanshaul** [comment]
Yea I think it makes sense too:
https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/issues/166

**Comment by etanshaul** [comment]
Closing this. The integrated JB plugin already used a whitelist, I just missed it the first time around: `AppEngineForbiddenCodeInspection#visitReferenceElement`

The only modification needed is to pull the whitelist class from the [common lib](https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/167/files) instead of the appcfg jar - this will happen as part of the SDK refactoring.
