### ISSUE TITLE
Cannot deploy to app engine after integrating the JetBrains google-app-engine-plugin

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/gcloud-intellij#786]
While testing the `merge` branch, I am unable to successfully deploy a web application to App Engine. 

After generating an App Engine project using the project generator, I created a run configuration to of type "App Engine (BETA) Deployment":

![screen shot 2016-07-14 at 11 36 50 am](https://cloud.githubusercontent.com/assets/1039411/16845539/4c0ab81c-49b7-11e6-84e6-d22ef3664026.png)

When running the configuration, I'm seeing this output: 

```
Deploying 'app-engine-random-service:war exploded'...
Created temporary staging directory: /private/var/folders/wz/93kfcdld3lg_nynvc_5t6d2400bzl9/T/gae-staging-reference-unity-1372154
Error: Could not find or load main class com.google.appengine.tools.admin.AppCfg
Failed to deploy 'app-engine-random-service:war exploded': Deployment failed due to an unexpected error while staging the project.
```

**Comment by etanshaul** [comment]
Run `gcloud components list` and make sure that 'gcloud app Java extensions' is installed. If not run: `gcloud components install app-engine-java`

**Comment by aslo** [comment]
That did it 😄 

Might we want to provide a more descriptive error message for this situation in the future?

**Comment by etanshaul** [comment]
Yes that would be nice, but we currently just pipe the output from gcloud. So short of parsing it we have no good way to determine what the error actually is at the moment.

**Comment by aslo** [comment]
Makes sense. I'll close this issue and perhaps we can follow up on that later on.

**Comment by etanshaul** [comment]
Thanks

**Comment by etanshaul** [comment]
see https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/issues/165

**Comment by patflynn** [comment]
when configuring the App Engine 'Gcloud' could we check installed
components and ask the user for permission to install the java component if
it's missing?
