### ISSUE TITLE
Move cloud SDK setting to a "global" google plugin setting

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#787]
The motivation for this is that we now will have components that rely on the SDK that are not tied to a Cloud configuration. Most notably the local server run for AE standard apps.

related to: #781

**Comment by etanshaul** [comment]
Note: for flex apps we need a way to prompt the user to apply the app engine facet to the project at the appropriate time. Since flex apps are just freeform web apps, we should probably do this at the time of attempting to deploy to GAE. We can do something like following which happens when an AE standard app is opened:

![image](https://cloud.githubusercontent.com/assets/1735744/16923269/55db2880-4ce7-11e6-9cf5-f4b2d7ec8551.png)

This will ensure that flex apps also have the facet configured (and the SDK since we are moving the SDK to the facet level).

**Comment by patflynn** [comment]
What aspect of the SDK are we moving to the facet level?

**Comment by etanshaul** [comment]
Based on offline conversation we decided not to move the SDK config to the facet level:

Instead we will move it a "global" plugin configuration level. Having the SDK config live at the facet (and therefore at the module) level doesn't provide extra value. This also simplifies the flow for flex applications since we won't need an app engine facet for flex just to provide the SDK.

**Comment by etanshaul** [comment]
closed via #808
