### ISSUE TITLE
Closing and restarting IntelliJ causes Google login state to reset

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#794]
Steps to reproduce:

1) Install the latest version of gcloud-intellij (0.9.7-beta)
2) Login using the Google login widget
2) close IntelliJ
3) restart Intellij

result:
The login widget shows that I'm logged out

expected result:
The login widget shows my logged in state from before closing IntelliJ.

This used to work, but I'm not sure when it stopped working. It should be tested in Android Studio as well.

**Comment by patflynn** [comment]
Thanks @chanseokoh who pointed this out.

**Comment by elharo** [comment]
FWIW, this is exactly how I would expect and want login to work. Of course, I'm mildly security paranoid.

**Comment by patflynn** [comment]
FYI this is working properly in Android Studio 2.2 preview 6.

**Comment by etanshaul** [comment]
Looks like this broke in version 0.9.3-beta of the account plugin. I just checked and it works in the previous version 0.9.2.4-beta

**Comment by patflynn** [comment]
Yeah I think this broke when I refactored it to a service. initalizeUsers is never getting called, which rings a bell for some reason.

**Comment by akerekes** [comment]
I'd let the user decide whether they want to be security paranoid or not
with defaulting to clearing it on exit.
