### ISSUE TITLE
unable to undeploy a AE standard VM=true app

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#828]
steps to reproduce:

1) Using a Java Maven based App Engine standard project (doubt Maven is important here)
2) add <vm>true</vm> to appengine-web.xml 
3) Do a deployment using our App Engine deployment run config
4) Observe that once deployment is complete the undeploy button is still disabled, as though it was a standard project.

**Comment by patflynn** [comment]
closing this as I am no longer able to reproduce.

**Comment by etanshaul** [comment]
I see this is still open so I'm closing. Feel free to re-open if its still an issue.
