### ISSUE TITLE
add analytics pings to newly integrated JB code

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#842]

**Comment by etanshaul** [comment]
This would include:

- local run / debug (probably include meta data to distinguish between these)
- new project wizard

I can't think of anything else.

**Comment by patflynn** [comment]
Maybe adding the facet? Can we track that?

**Comment by etanshaul** [comment]
Yes, but it might make more sense to move it up one level to adding framework support (which adds the facet itself). But it is possible to add the facet without framework support, so maybe it should track this too (with proper deduplication).
