### ISSUE TITLE
Remove datanucleus, jpa/jdo enhancers from the integrated plugin code

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#848]
And investigate what support (if any) is needed for already existing projects created with the old plugin

**Comment by etanshaul** [comment]
@patflynn - the PR for this issue would essentially remove all configuration from the app engine facet (all there was was ORM related stuff). And since a facet with no configuration is not a valid facet, I will have to remove the facet altogether, keeping in mind that we can reintroduce it later when we need it. Unless you can think of an alternative?

**Comment by patflynn** [comment]
How about we remove this as part of the change to include the libraries in the deps docs we reviewed last week?

**Comment by etanshaul** [comment]
This change to remove ORM support is already a bit large (many files and code removed). My concern is that a combined PR will be hard to review. I'll see if there's a way for me to complete this PR - removing ORM support - without removing the facet.

**Comment by patflynn** [comment]
a placeholder piece of state?  Can you hide it from the UI?

**Comment by etanshaul** [comment]
Yea I was able to keep it as a placeholder. There was no need to hide anything in the UI - the facet page is now just blank (which will change when we add lib configuration here).
